config/routes.rb
SPARKs::Application.routes.draw do
  resources :questions

  resources :papers

  resources :authors
  resources :sessions
  get "signin" => "sessions#new", :as => "signin"
  get "signout" => "sessions#destory", :as => "signout"
  
  get "home/index"

  root :to => 'home#index'

end

app/models/paper.rb
# == Schema Information
#
# Table name: papers
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  file       :string(255)
#  demo       :string(255)
#

class Paper < ActiveRecord::Base
  belongs_to :author
  has_many :questions
  attr_accessible :title, :author_id, :file, :demo
  mount_uploader :file, FileUploader
  mount_uploader :demo, DemoUploader
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])
    @paper.author_id = current_author.id
    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end

private
  def set_paper
      @paper = Paper.find(params[:id])
  end

  def user_params
      params.require(:paper).permit(:title, :file, :demo)
  end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= simple_form_for(@paper) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    
  </div>

  <div class="field">
      <%= f.label :file %><br>
      <%= f.file_field :file %>
  </div>

  <div class="field">
      <%= f.label :demo %><br>
      <%= f.file_field :demo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
	<% if paper.author_id == current_author.id%>
  	<tr>
    	<td><%= paper.title %></td>
    	<td><%= paper.author %></td>
    	<td><%= link_to 'Show', paper %></td>
    	<td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    	<td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %><br />
<%= link_to 'Sign out', signout_path%>

app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Author:</b>
  <%= @paper.author.name %>
</p>

<p>
  <b>File:</b>
  <%= @paper.file %>
</p>

<p>
  <b>Demo:</b>
  <%= @paper.demo %>
</p>

<!--
<table>
<% Question.find_by_paper_id(@paper.id) do |question| %>
  	<tr>
    	<td><%= question %></td>
    	<td><%= link_to 'Show', question %></td>
    	<td><%= link_to 'Edit', edit_question_path(question.object_id) %></td>
    	<td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
<% end %>
</table>

<%= link_to 'New Question', new_question_path(@paper_id)%>
-->	
<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>